server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  servlet:
#    multipart:
#      max-file-size: 2Mb
#      max-request-size: 2Mb
        
        
mybatis:
  mapper-locations: classpath:com/pro/mapper/xml/*.xml
  type-aliases-package: com.pro.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


    


